# Generated by Django 2.1.2 on 2019-01-16 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181211_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('twitter_user_id', models.CharField(max_length=191)),
                ('tweet_id_str', models.CharField(max_length=100)),
                ('date_posted', models.DateField()),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
