# Generated by Django 2.1.2 on 2019-01-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_already_in_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='already_in_twitter',
            name='user',
            field=models.CharField(default=False, max_length=10),
            preserve_default=False,
        ),
    ]
