# Generated by Django 2.1.2 on 2019-01-21 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        ('users', '0005_auto_20190117_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='twitter_user_id',
        ),
        migrations.AddField(
            model_name='post',
            name='associated_social_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialaccount.SocialAccount'),
        ),
    ]
