# Generated by Django 2.1.2 on 2019-01-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_already_in_twitter_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='already_in_twitter',
            name='user',
            field=models.CharField(default=False, max_length=10),
        ),
    ]
