# Generated by Django 2.1.2 on 2019-01-11 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190107_2012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='already_in_twitter',
        ),
    ]
