# Generated by Django 2.1.2 on 2019-01-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_already_in_twitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='already_in_twitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=False, max_length=10)),
                ('already_in_twitter', models.CharField(default=False, max_length=10)),
            ],
        ),
    ]
