# Generated by Django 2.1.2 on 2019-01-31 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_already_in_twitter_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='short_representation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
