# Generated by Django 2.1.2 on 2019-01-21 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('tweet_id_str', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField()),
                ('associated_social_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='socialaccount.SocialAccount')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
